name:                aywins
version:             0.1.0.0
github:              "githubuser/aywins"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Are ya winning son? - A Discord bot for tracking game scores

dependencies:
- base >= 4.7 && < 5
- discord-haskell
- esqueleto
- persistent
- persistent-sqlite
- persistent-template
- text
- time
- bytestring
- bytestring-conversion
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  aywins-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aywins
    when:
    - condition: false
      other-modules: Paths_aywins

tests:
  aywins-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aywins
    when:
    - condition: false
      other-modules: Paths_aywins
